In [2]:
import pandas as pd
music_data = pd.read_csv('music.csv')
music_data

    age  gender       genre
0    20        1     HipHop
1    23        1     HipHop
2    25        1     HipHop
3    26        1       Jazz
4    29        1       Jazz
5    30        1       Jazz
6    31        1  Classical
7    33        1  Classical
8    37        1  Classical
9    20        0      Dance
10   21        0      Dance
11   25        0      Dance
12   26        0   Acoustic
13   27        0   Acoustic
14   30        0   Acoustic
15   31        0  Classical
16   34        0  Classical
17   35        0  Classical

In [23]:
from sklearn.tree import DecisionTreeClassifier

X = music_data.drop(columns=['genre'])
y = music_data['genre']
model = DecisionTreeClassifier()

model.fit(X,y)

#model.predict takes a 2D array [[]]
y_pred = model.predict([[18,1],[37,0]]) 
y_pred

c:\Users\bonfa\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['HipHop', 'Classical'], dtype=object)

In [1]:
# Calculating the acurracy score of the program

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model.fit(X_train, y_train)
predictions = model.predict(X_test)

score = accuracy_score(y_test, predictions)
score

NameError: name 'X' is not defined